### PR TITLE
Docker related DevOps Project.

### PR DESCRIPTION
**Pull request by 0904-mansi**
Hello @ajeetraina sir !! This is an overview of my project. Please check it out if it's ok i will complete my explanation with jenkins 2 same as docker.
Thank You..

### CODE REVIEW

**Comment by ajeetraina** [comment]
Hello @0904-mansi It is important to understand the directory structure of this community site:

```
pwd
/content/en/docs
ajeetraina@Ajeets-MacBook-Pro docs % tree
.
├── _index.md
├── ansible
│   └── _index.md
├── docker
│   ├── _index.md
│   └── jenkins
│       └── _index.md
├── grafana
│   └── _index.md
├── images
│   └── logos
│       ├── ansible.png
│       ├── docker.png
│       ├── grafana.png
│       ├── kubernetes.png
│       ├── prometheus.png
│       └── terraform.png
├── kubernetes
│   └── _index.md
├── prometheus
│   └── _index.md
└── terraform
    └── _index.md

9 directories, 14 files
ajeetraina@Ajeets-MacBook-Pro docs % 
```

First, you need to add your content to specific technology and this is in the form of folders.
Say, you want to contribute towards Docker, then you need to go to docker folder first:

```
 pwd 
/Users/ajeetraina/projects/community/content/en/docs/docker
ajeetraina@Ajeets-MacBook-Pro docker % tree
.
├── _index.md
└── jenkins
    └── _index.md

1 directory, 2 files
```

Then under that you need to create a directory called jenkins 2 and then dump the content into it by creating a file called _index.md.

Hope it helps.

**Comment by ajeetraina** [comment]
Also, you mentioned the command:

```
docker build . -t getintodevops-hellonode:1
```

Where is the Dockerfile? How would anyone find the location of Dockerfile?

**Comment by 0904-mansi** [comment]
> Also, you mentioned the command:
> 
> ```
> docker build . -t getintodevops-hellonode:1
> ```
> 
> Where is the Dockerfile? How would anyone find the location of Dockerfile?

Ok @ajeetraina sir, I will fix everything as you mentioned above. Thank you

**Review by ajeetraina — APPROVED** [review]

**Comment by ajeetraina** [comment]
Keep contributing. @0904-mansi

**Pull request merged**
